version: "3.3"

services:
  grafana:
    container_name: grafana_test
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    restart: unless-stopped

  influxdb:
    container_name: influxdb_test
    image: influxdb:latest
    ports:
      - 8086:8086
    volumes:
      - influxdb2:/var/lib/influxdb2
    restart: unless-stopped

volumes:
  influxdb2: